Add Overlays for Argo on OCP4 with slightly modified role definitions
AICoE/idh-manifests pull request #187
Opened 2021-10-14 07:14 UTC by gmfrasca

2021-10-14 07:15 UTC, sesheta commented
@gmfrasca: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 0cc7574f405db56ffb4b77adbd15213043d7a219 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/AICoE_idh-manifests/187/pre-commit/1448547854833422336) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=idh-manifests&pr=187). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Agmfrasca). Please help us and [open an issue](https://github.com/AICoE/idh-manifests/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-10-14 08:45 UTC, lucferbux commented
/retest

2021-10-14 08:47 UTC, sesheta commented
@gmfrasca: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 0cc7574f405db56ffb4b77adbd15213043d7a219 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/AICoE_idh-manifests/187/kustomize-build/1448547853575131136) | true | `/test kustomize-build`
aicoe-ci/prow/pre-commit | 0cc7574f405db56ffb4b77adbd15213043d7a219 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/AICoE_idh-manifests/187/pre-commit/1448570753220874240) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=idh-manifests&pr=187). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Agmfrasca). Please help us and [open an issue](https://github.com/AICoE/idh-manifests/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-10-14 08:48 UTC, lucferbux commented
It looks good to me, but I would need to review the role definitions. A part from that it needs new lines in some of the files.

2021-10-14 08:52 UTC, sesheta commented
@gmfrasca: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 0cc7574f405db56ffb4b77adbd15213043d7a219 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/AICoE_idh-manifests/187/pre-commit/1448570753220874240) | true | `/test pre-commit`
aicoe-ci/prow/kustomize-build | 0cc7574f405db56ffb4b77adbd15213043d7a219 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/AICoE_idh-manifests/187/kustomize-build/1448570752344264704) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=idh-manifests&pr=187). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Agmfrasca). Please help us and [open an issue](https://github.com/AICoE/idh-manifests/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-10-14 08:53 UTC, lucferbux requested changes

2021-10-14 08:53 UTC, lucferbux commented on argo/overlays/ocp4.dh-prod-argo/deployments/argo-server_patch.yaml
> +        beta.kubernetes.io/os: linux
New line

2021-10-14 08:53 UTC, lucferbux commented on argo/overlays/ocp4.dh-prod-argo/deployments/workflow-controller_patch.yaml
> +        beta.kubernetes.io/os: linux
New line

2021-10-14 14:24 UTC, anishasthana reviewed
/lgtm

2021-10-14 18:54 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **anishasthana** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fidh-manifests).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/idh-manifests/blob/production/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["anishasthana"]} -->

2021-10-14 19:07 UTC, sesheta commented
@gmfrasca: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 67e0f1ce648ed3073ebe609b619686fbabfd1e00 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/AICoE_idh-manifests/187/pre-commit/1448723902049030144) | true | `/test pre-commit`
aicoe-ci/prow/kustomize-build | 67e0f1ce648ed3073ebe609b619686fbabfd1e00 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/AICoE_idh-manifests/187/kustomize-build/1448726294802993152) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=idh-manifests&pr=187). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Agmfrasca). Please help us and [open an issue](https://github.com/AICoE/idh-manifests/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-10-14 19:25 UTC, accorvin commented
/lgtm

2021-10-14 20:07 UTC, anishasthana commented
/retest

2021-10-14 20:08 UTC, sesheta commented
@gmfrasca: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 67e0f1ce648ed3073ebe609b619686fbabfd1e00 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/AICoE_idh-manifests/187/kustomize-build/1448726294802993152) | true | `/test kustomize-build`
aicoe-ci/prow/pre-commit | 67e0f1ce648ed3073ebe609b619686fbabfd1e00 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/AICoE_idh-manifests/187/pre-commit/1448742337579585537) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=idh-manifests&pr=187). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Agmfrasca). Please help us and [open an issue](https://github.com/AICoE/idh-manifests/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-10-18 07:44 UTC, gmfrasca commented
Just to comment, I've found that `kustomize build` was failing for this application even before/without the contents of this PR. specifically, it appears to not like the inclusion of a resource from raw.githubusercontent.com as kustomize only allows very specific URL domains for github.

2021-10-18 20:38 UTC, sesheta commented
@gmfrasca: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 67e0f1ce648ed3073ebe609b619686fbabfd1e00 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/AICoE_idh-manifests/187/kustomize-build/1448742337579585536) | true | `/test kustomize-build`
aicoe-ci/prow/pre-commit | 607d0ca5bb9caec1e3e394e31025ac12b7c67f6b | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/AICoE_idh-manifests/187/pre-commit/1450199322317557760) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=idh-manifests&pr=187). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Agmfrasca). Please help us and [open an issue](https://github.com/AICoE/idh-manifests/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-10-18 20:40 UTC, anishasthana reviewed
/lgtm

2021-10-18 20:40 UTC, anishasthana commented
/retest

2021-10-18 20:48 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-10-18 20:53 UTC, anishasthana approved these changes
/lgtm

2021-10-18 20:53 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/idh-manifests/pull/187#pullrequestreview-782568145" title="LGTM">anishasthana</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fidh-manifests).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/idh-manifests/blob/production/OWNERS)~~ [anishasthana]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-10-18 21:01 UTC, merged